### PR TITLE
add node support

### PR DESCRIPTION
**Pull request by jessetane**

### CODE REVIEW

**Comment by WebReflection** [comment]
not happening here, sorry, this project is for Web polyfills. For NodeJS, use [basichtml](https://github.com/WebReflection/basicHTML/#readme) or others.

```js
const {CustomEvent} = require('basichtml');
```

**Comment by jessetane** [comment]
Well. I'm specifically looking for esm support, so looks like basichtml isn't going to work. Was there something else you'd recommend having a look at?

**Comment by jessetane** [comment]
https://ungap.github.io/

Also the ungap project page specifically states that node support is a goal, so you might want to fix that...

**Comment by WebReflection** [comment]
The entirety of the code coverage here is done in NodeJS, hence every module supports it:
https://github.com/ungap/custom-event/blob/master/test/index.js

_basicHTML_ **is** the DOM used in here, no extra bloat for Node will land since _basicHTML_ covers all DOM use cases, and NodeJS use cases on the Web are a waste of bytes.

You can `import basichtml from 'basichtml';` too, as NodeJS imports are compatible out of the box with CommonJS modules, as these are still first class citizens in node core.

**Comment by WebReflection** [comment]
P.S. I'll remove NodeJS though, as it's meant to underline modules can be required/imported by Node, not that modules should work in Node. Node has no DOM, so 90% of ungap makes no sense in there, all other things are natively supported since version 8, 10, or above.

**Comment by jessetane** [comment]
What I'm trying to do is write event handling code that works in node and browser. Previously I achieved this by using a bundler and bringing node's eventemitter to the browser, but I'd like to also have the inverse option (eventtarget, customevent in node). For what it's worth, ungap/event-target works out of the box (except you can't import the esm in node, see https://github.com/ungap/event-target/pull/2). In any case, basichtml doesn't work in the browser, so I'm not sure it solves my particular problem.

**Comment by WebReflection** [comment]
basichtml works in the browser too https://github.com/WebReflection/basicHTML/blob/master/web.js

**Pull request closed without merging**
